# Generated by Django 2.2.12 on 2020-10-26 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_comprasdetalle_comprasencabezado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprasdetalle',
            old_name='iva_prod',
            new_name='iva',
        ),
        migrations.RemoveField(
            model_name='comprasdetalle',
            name='iva_total',
        ),
        migrations.RemoveField(
            model_name='comprasdetalle',
            name='precio_sin_iva',
        ),
    ]
